### ISSUE TITLE
Проблем със зареждане на статични файлове в проекта заради Spring security.

### ISSUE THREAD

**Issue by Stefan-Markov** [luchob/softuni-music-db#1]
Здравейте, лъчезар. При използването на Spring Security ми позволява по неразбираеми за мен причини, css файлове само за index. Когато искам да достъпя login или registration, ми зарежда само html файла без css. Прегледах в нета хиляди варианти, но нищо не сработи. Дали ще може да се погледне къде бъркам ? https://github.com/StefanFMarkov/project

**Comment by luchob** [comment]
Здравей!

Разбира се, че може! Бъркаш в начина, по който си дефинирал линка. По-точно тук:

```
<link rel="stylesheet" href="css/style_footer.css">
```

Това означава, че линка ти е релативен спрямо _текущия_ път, който например на логина е `http://localhost:8080/user`. В действителност, ако отвориш девелопърската конзола, ще видиш и самата заявка за css файла:

<img width="863" alt="Screenshot 2021-03-07 at 15 51 52" src="https://user-images.githubusercontent.com/10339738/110242312-2d624380-7f5e-11eb-8071-9b20cdf4d625.png">

Обърни внимание къде търси css файла (Request URL) - там няма нищо. По-правилното е:

```
<link rel="stylesheet" href="/css/style_footer.css">
```

Когато започва с `/` това е път релативен на самия хост, т.е. `http://localhost:8080`.

Разбира се, най-правилното е да използваш link фунционалността на thymeleaf (което ще работи правилно дори и да се деплойне като war, нещо за което споменахме миналата лекция). Ето ти и пример:

```
<link rel="stylesheet" th:href="@{/css/style_footer.css}">
```

Сигурен съм, че се досещаш вече защо css-a работи само на `http://localhost:8080/` Надявам се, това да ти помогне! 

Поздрави,
Л.
