### ISSUE TITLE
COVID-19 issue

### ISSUE THREAD

**Issue by luchob** [luchob/softuni-music-db#10]
Привет, банда! 

За съжаление и аз станах жертва на това заболяване. За сега го карам тежко и не съм в състояние да отговарям на въпроси тук, постоянно имам температура и съм изнемогнал... И все пак още един съвет от мен - пазете се, това не е шега.

Поздрави и надявам се да успея да си побъбря на още лекция две с вас!

Поздрави,
Л.

**Comment by StanislavI285** [comment]
Бързо оздравяване, Лъчо!

**Comment by todorgospodinov** [comment]
С теб сме. Ще се справиш! Чакаме те обратно на линия, момче!

**Comment by ivaka4** [comment]
Бързо оздравяване!

**Comment by dddobrev** [comment]
Бързо оздравяване Лъчо.  Ще се оправиш, ще пием бира и ще караме мотори лятото. Поздрави от морето!
Митко

**Comment by luchob** [comment]
Хей, благодаря на всички! :-) 
Много коварна и подла гад се оказва това нещо, направо не го очаквах. Ама няма да му се давам, де. Тези дни вече има часове, в които ми просветва, така че ще се помъча да се разнообразявам и да отговарям тук. Ако всичко върви добре, надявам се следващия петък да съм отново на крака и да побъбрим за 3-4 часа на лекцията. Но... Гадината е напълно непредвидима, та ще видим. Както те отпуска за часове или ден, след това изведнъж те хваща за гушата и пак отначало...

Пазете се и бъдете здрави :-)

**Comment by BojidarVn** [comment]
Дано се оправиш бързо и без усложнения!

**Comment by AswAce** [comment]
Бързо оздравяване и благодаря за помоща.

**Comment by DoytchoConkov** [comment]
Пожелавам ти бързо оздравяване

**Comment by ElenaTasheva** [comment]
Бързо възстановяване! Чакаме те обратно на линия! Благодаря за съдействието до сега!

**Comment by Bozhidarov8609** [comment]
Бързо оздравяване

**Comment by luchob** [comment]
Айде, да го затваряме това нещо, да спре да ми напомня малките POST-ковид драмички :-) Благодаря на всички за подкрепата ви, в тези моменти е наистина важно да чуеш окуражителна дума. 

Та... на този етап няма да се мре, яко да се мре. Преди седмица това съвсем не изглеждаше сигурно :-)

Бъдете здрави и благодаря!
