### ISSUE TITLE
Проблем с ъплоада на снимка

### ISSUE THREAD

**Issue by AswAce** [luchob/softuni-music-db#11]
Здравей.
Oпитвам се да си кaча снимки в проекта, но още на биайдинг модела ми дава null като стойност и ерор на полето MultipartFile пробвах с някой други гайдове в интернет да реша проблема но не успях също, добавих 1 dependancy 
<dependency>
			<groupId>com.cloudinary</groupId>
			<artifactId>cloudinary-http44</artifactId>
			<version>1.3.0</version>
		</dependency>
което ако махна почва да ми гърми целия проект.
Това е линк към контолера ми в който не минава самамата снимка:
https://github.com/AswAce/MedicalFiles/blob/main/src/main/java/medical/medical/files/web/DoctorController.java

Toва е страницата с форма: 
https://github.com/AswAce/MedicalFiles/blob/main/src/main/resources/templates/doctor-profile/add-doctor-profile.html
Всички други полета си се мапват без проблем

**Comment by luchob** [comment]
Здравей!

Извинявай за бавния отговор, но ако видиш тук - https://github.com/luchob/softuni-music-db/issues/10 - късмета не е с мен тези дни. Веднага виждам проблем във формата ти, който ще пречи на ъплоада. Нямаш `enctype` във `form` тага. Например, трябва да изглежда ето така:

```
<form ... enctype="multipart/form-data">
```

Ако това не помогне, пиши тук. Като ми просветва, ще гледам да помагам, пък живот и здраве ми се иска до петък да се възстановя :-)

Поздрави,
Л.
