### ISSUE TITLE
Проблеми с писане на тестове

### ISSUE THREAD

**Issue by Stefan-Markov** [luchob/softuni-music-db#14]
Здравейте, може ли някакви насоки и примери как да започна с писането на тестове, защото нямам никакъв успех до сега от дни. Приложим съм в проекта семпъл тест, с който да покажа как като се стартира и започва да гърми всичко, търси bean-ове, който не му трябват за теста и така е от два дни. 
https://github.com/StefanFMarkov/Motorious

**Comment by luchob** [comment]
Ехееее, стига - няма такива неуспехи от дни, успехите трябва да почнат от днес :-) Днес ми е първия ден в който имам истински напредък с КОВИДчо, така че деня е специален! Дай да започнем с един интеграционен тест на home controller-a, нещо съвсем простичко. Трябва ти още един application.properties в test/resources, нещо дето да настройва работата с H2 in memory DB:

```
cloudinary.api-key=128364628252436
cloudinary.api-secret=test
cloudinary.cloud-name=dxj5jv2uw
server.port=8080
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.mvc.hiddenmethod.filter.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
```
Интеграционните тестове се изпълняват с inmemory DB. След това нека да напишем първите 2 теста:

```
@SpringBootTest
@AutoConfigureMockMvc
@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2)
class HomeControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @WithMockUser(username = "stef4o")
    @Test
    void testHome() throws Exception {
        mockMvc.perform(MockMvcRequestBuilders
            .get("/home"))
            .andExpect(status().is2xxSuccessful())
            .andExpect(view().name("home"))
            .andExpect(model().attribute("user", "stef4o"));
    }

    @WithAnonymousUser
    @Test
    void testHomeAuthentication() throws Exception {
        mockMvc.perform(MockMvcRequestBuilders
            .get("/home"))
            .andExpect(status().is3xxRedirection())
            .andExpect(MockMvcResultMatchers.redirectedUrlPattern("**/user/login"));
    }
}
```

**Comment by Stefan-Markov** [comment]
Здравейте, приложих примерите от по-горе. Ако application.properties седи на test/resourses не си я взима и яко си гърми с ненамерени beans. Ако я преместя application.properties в test/java/resources/... си я взима и започва да вади DLL от h2 базата, но пак дава грешки.

**Comment by luchob** [comment]
Commit-нал ли си за да погледна?

**Comment by Stefan-Markov** [comment]
Да, с новите корекции.

**Comment by Stefan-Markov** [comment]
Здравейте, проблема който е в невъзможността да си генерира beans през новия application.properties е, че не разчиташе променливата за ключ на cloudinary. Когато го вкарам реалния ключ започва работа, дори имам собствено ръчно написан тест, който е свръх прост. Сега ще прегледам отново лекцията от вчера и ще следвам насоките. Също така вие споменахте, че с integration test изкуствено се вдига coverage. В момента само от 4 теста ми показва 63% coverage  на класовете.

**Comment by luchob** [comment]
Да, тестовия контекст изисква всичко, което и нормалния, т.е. ако нещо няма в application.properties ще се оплаче. Добрата новина е, че си казва какво му липсва. Един единствен интеграционен тест вдига ковириджа драстично, защото вдига всички бийнове и конфигурации, които са много редове код. Давай смело още малко, щом си на 63% лесно ще ги вдигнеш с още 10-на процента. :-)
