### ISSUE TITLE
Кликане на бутони

### ISSUE THREAD

**Issue by vasilev02** [luchob/softuni-music-db#15]
Добър вечер ! Забелязах, че когато си стартирам приложението и примерно добавям продукт или коментар при правилен input ако наспамя бутона ще ми направи примерно 10 еднакви entity-та и после при добавяне на същото entity получавам грешка query did not return a unique result: 9 (когато проверявам дали даден продукт същуствува и нали се взима от db-то, но като са наспамени и затова се получава грешката)... Как може да се оправи тази грешка ? Благодаря предварително !!!

**Comment by luchob** [comment]
Здравей! Говориш за този проект или? Щото става въпрос за някакъв продукт... Може ли повече детайли или направо линк към проект? Принципно ако добавяш продукт/коментар и ползваш JS това е чест проблем и се решава с javascript:

1. Click
2. Disable button
3. Fetch API
4. Enable button

:-)
