### ISSUE TITLE
проблем със search-bar

### ISSUE THREAD

**Issue by DesislavaGetova-Petrova** [luchob/softuni-music-db#16]
Здравей Лъчо, search-bar ми работи само докато не добавя коментар към някой от обектите, които подлежат на търсене. Не успявам да се справя с проблема, моля за малко помощ. https://github.com/DesislavaGetova-Petrova/TheProject

**Comment by luchob** [comment]
Здравей, Деси! Разбира се, че може помощ. Първо за причината за проблема ти. От RestController-a връщаш ентити. Вместо това си направи view model. Аз щях да преправям нашия проект и да се карам, че така сме го направили :-) :-) Ето повече детайли:
```
public class VideoEntity extends BaseEntity{
  
    private Set<CommentEntity> comments;
}
```

```
public class CommentEntity extends BaseEntity {

   private VideoEntity videoEntity;
}
```

Jackson тръгва да сериализира видеото, после коментара в който има циклична референция към същото видео, в което има същия коментар и т.н. Т.е. получава се безкраен цикъл. 

Най-чистото решение е да връщаш view model от рест контролера си. Най-мръсното е да използваш `JsonIgnore` анотация върху коментарите. Тази анотация ще забрани на jackson да сериализира коментарите. Не го препоръчвам.

Надявам се да съм бил полезен!
Л.

**Comment by DesislavaGetova-Petrova** [comment]
Благодаря много! Ще преправя да връща view model, както ми препоръчвате. Бързо възстановяване!
Д.
