### ISSUE TITLE
java.lang.IllegalStateException: Failed to load ApplicationContext

### ISSUE THREAD

**Issue by Elizabetaa** [luchob/softuni-music-db#18]
При стартиране на теста за контролера не може да създаде beans  и хвърля грешка 
https://github.com/Elizabetaa/MotoTuning

**Comment by luchob** [comment]
Добра вечер! Да, защото:

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'cloudinary.cloud-name' in value "${cloudinary.cloud-name}"
````

Тъй като вдигаш целия спринг контекст с тест, в тестовия `application.yml` е редно да има всичко, което е необходимо за да вдигнеш и истинския контекст. В случая нямаш настройки за клаудинари. Може да добавиш:

```
cloudinary:
    cloud-name: test
    api-key: test
    api-secret: test
```
Така Spring ще може да задоволи всички dependencies и контекста ще може да стартира.

Желая здраве :-)
Л.

**Comment by Elizabetaa** [comment]
Благодаря много! Бързо оздравяване :)
