### ISSUE TITLE
Отново въпрос за тестовете(Количката)

### ISSUE THREAD

**Issue by ivaka4** [luchob/softuni-music-db#20]
Здравей, 
Опитвам да направя тестове за достъп към количката но ми хвърля тази грешка.
![image](https://user-images.githubusercontent.com/69511821/112882262-66ad4f80-90d5-11eb-9189-7335be5ec10b.png)
А когато опитвам да инициализирам юзър с продукти в количката и ми хвърпя Detached to persist грешка. Ако може малко помощ.

Линк към [GIT](https://github.com/ivaka4/watch-shop)

**Comment by luchob** [comment]
Привет! Предлагам следното бързо решение:

1. Махаме от теста:
```
@MockBean
    private UserService userService;
```

2. User-a в withmockuser става пешо.
3. В init метода създаваме обекта ето така:
```
       userEntity.setIsEnabled(true);
        userEntity = userRepository.save(userEntity);

        userEntity.setCart(List.of(product));
        userEntity = userRepository.save(userEntity);
```
4. Правим не само init, но и teardown, нещо като колегата тук, последния коментар - https://github.com/luchob/softuni-music-db/issues/19

Поздрави,
Л!
