### ISSUE TITLE
Проблем с тестване на контролери

### ISSUE THREAD

**Issue by dpopov-sc** [luchob/softuni-music-db#21]
Здравей Лъчо, моля те, ако имаш възможност, за малко помощ с тестовете на контролерите. 
Идеята на проекта е всеки юзър да вижда собствените си коли и всяка кола да вижда собствените си ентитита (различни видове такси и информация за поддръжка). 

Още на първия тест в CarControllerTest, където искам да покажа всички коли на логнатия user, получавам следната грешка:

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "com.clydefrog.cardiary.models.entities.UserEntity.getId()" because "userEntity" is null

Предполагам не трябва да тествам с мокнат юзър, а да му подам по някакъв начин инициализирания в мокнатата база. Може би това ще е проблем в тестването на всички "подчинени" view-та. Не знам как точно да продължа, понеже  основната логика зависи от този контролер.

https://github.com/dpopov-io/cardiary

**Comment by luchob** [comment]
Здравей!

Погледнах. Трябва да имаш инициализиран юзър в мокнатата база. Например, трябва да имаш в юзър репозиторито юзър pesho за да работи това:

```
   @Test
    @WithMockUser(value = "pesho", roles = {"ADMIN", "USER"})
```

Като гледам и initUser-a това никога няма да стане:

```
        if (userRepositoryMock.count() == 0){
```

Защото нали имаш вече 2 юзъра, които си инициализирал с ДБ Инит. 

Тъй че:
1. Наливаш юзър в мокнатата база със същото име, което е в WithMockUser
2. Внимаваш да почистваш след всеки тест, виж последния коментар тук - https://github.com/luchob/softuni-music-db/issues/19

И така ще станат нещата, ще се връща UserEntity и няма да хвърляш NPE.

Успех,
Л.

**Comment by dpopov-sc** [comment]
Работи! :)

Не знам защо си мислех, че за всеки отделен тест на контролер получавам празна база, която трябва да се инициализира наново.

Много благодаря за помощта!

Поздрави,
Димитър
