### ISSUE TITLE
Data Initialization

### ISSUE THREAD

**Issue by yavor300** [luchob/softuni-music-db#22]
Здравей, Лъчо!

В проекта ми се налага да insert-на данни в базата, когато се стартира за първи път.

Данните не са малко на брой и се чудя как да подходя.

Да ги insert-вам отделно всички с sql файл или да ги попълня всички entity-та на ръка и да ги saveAndFlush-на в базата (if repository.count==0).

Tака правехме на упражненията, но данните бяха малко на брой, примерно един User.

Ти какво би направил, когато ти се налага да добавиш данни при първоначалното ти стартиране на проекта?

Лека работа и успешен ден!

**Comment by luchob** [comment]
Здрасти! Аз бих използвал библиотеки от сорта на liquibase, но тъй като за съжаление не я показахме, може би е добре да се спреш на импорт от файл. Например виж тук:

https://github.com/luchob/softuni-music-db/blob/master/src/main/java/bg/softuni/musicdb/service/impl/ArtistServiceImpl.java#L30

В контеста на тези проекти ми се струва разумно решение.

Поздрави,
Л.
