### ISSUE TITLE
Fetch issues 

### ISSUE THREAD

**Issue by AswAce** [luchob/softuni-music-db#23]
Здравей.
Опитвам се да fetchна info от базата в арей и после да го итерирам и зависимост от стойностите после си добавям клас към конкретен дом елемнт.
Кода работи ако съм вкарал Демо арей който не е фетчнат, но просто като се фетчва арея не се пълни преди да стигне до фунцията за итериране.
Мъчуих се да ги нагласям с async и аwait ,но просто не успях

https://github.com/AswAce/MedicalFiles/blob/main/src/main/resources/static/js/body.js
Toва е линк към JS

**Comment by luchob** [comment]
Привет! Малко съм объркан - защо са ти async, await или каквото и да е по-сложно? Погледни феч функцията, която сме сложили в скрита на сърч бара като пример - https://github.com/luchob/softuni-music-db/blob/master/src/main/resources/static/js/search-bar.js#L6

Тя е вътре в самия файл, което означава, че се изпълнява веднага при зареждането на скрипта. При теб това не е така, значително по-сложно е. Опитай да изкараш функцията навън или просто да я извикваш при някакво събитие.

Освен това ми е трудно да пусна проекта. Reviews ентитито се казва фиийд бек:

```
@Entity(name = "feedback")
public class ReviewsEntity
```
и хибернейт се сърди, ресурсите може да се налеят само под уиндоус, нямам дори идея как да пресъздам проблема...

**Comment by AswAce** [comment]
Успях да го оправя като сложих evenListener ,но сега пък като си логна юзера ме пшрепраща на рест контролера вместо на Home page и ми вади данните на бял фон.
Имам и сърч  rest controller но там не дава този проблем.

**Comment by AswAce** [comment]
успях да го оправя благодаря за помоща
