### ISSUE TITLE
Въпрос относно проекта

### ISSUE THREAD

**Issue by ivaka4** [luchob/softuni-music-db#24]
Здравей отново, с риск да стана малко досаден и нахален.

Ако имаш време и желание да погледнеш, как въри проекта ми и да кажеш мнение по него. В момента направих всички тестове минават около 60% имам coverage. Логиката почти не съм я променял имам 1 интерсептор търсачка с AJAX и добаваня махане на продукти едитване и количката и ордъри, за сега. В момента мисля да добавя няколко подобрения в профил пейджа да излизат ордърите и се чудя сега или след курса да добавя AOP логовете. Блога не съм го оправил все още, но мисля след като мине защита или като предам да променя количката да направя отделна база за нея и да бъде и тя с AJAX, но в момента не искам да я променям, защото трябва да променям и другите ентита. Като цяло в момента мисля да допиша още тестове и ако имам време да оправя блога и сортировката в /shop отново с AJAX, ако не остане време ще бъде след защитата.

Линк [Watch-Shop](https://github.com/ivaka4/watch-shop)

**Comment by luchob** [comment]
Привет, харесва ми как е структуриран. Идеята с интерсептора е хитра, изкефих се :-)  Има и някои неща, които лично аз бих променил, но не искам да твърдя, че мнението ми е меродавно.
1. Йерархията с ексепшъните е малко прекалено раздута. По-добре е да има по-малко и generic ексепшъни.
2. Не е много добре юзъра ти, който е централно ентити да съдържа релации към продукти, блогове и т.н. За предпочитане е юзъра да е юзър, останалото може да го направиш с JPQL. Почти съм сигурен, че ще стане и по-четимо и читаво, да не говорим за някои перформънс благини.
3. Има и други малки неща - като например, опитах се да се регистрирам, но ако имам грешки във формата не ми запази инпута. Добавянето на продукт беше малко странно. Има и дреболии - може например цената да е дробна и неотрицателна и т.н. Просто трябва още малко работа, да се пипне.
4. Ако искаш да е като рекламка за по-натам, вкарай малко примерни продукти, за да може човек да си го отвори и да почне да зяпа.
5. Имаш някакви @Transactional анотации на get заявките в сървисите - това защото имаш лейзи релации ли е? Действително ли са нужни?
6. findLatest() - това в продукт репото - може да се опиташ да го направиш с пейджъбъл, представи си, че имаш 1 000 000 продукти. Мисля, че е добро упражнение. Все пак целта е да се упражняваш.

И такива дреболийки. Сигурен съм, че ще вземеш изпита, но... какво от това :-) Нататък е борбата, затова си стягай проекта и давай газ - ще ти послужи натам.
