### ISSUE TITLE
Проблеми с Тестове

### ISSUE THREAD

**Issue by TeoKarakashev** [luchob/softuni-music-db#26]
Привет, привет!
Имам проблеми с интегрирането на тестовата база данни, поради някаква причина си пречи с нещата, които CommandLineRunner-а инициализира при стартиране и работи само ако са закоментирани. Голяма част от тестовете ми дават следната грешка и не мога да разбера къде бъркам 
![image](https://user-images.githubusercontent.com/77853711/113132642-69b85500-9227-11eb-9bb2-539af05b63db.png)
https://github.com/TeoKarakashev/Softuni-Spring-Web-Project

**Comment by luchob** [comment]
Бонджорно! Ако се вгледаме по-подробно в ексепшъна:

```
Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 4; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 4

	at com.softuni.service.impl.BrandServiceImpl.findByName(BrandServiceImpl.java:56)
	at com.softuni.service.impl.BatServiceImpl.save(BatServiceImpl.java:89)
```

Гърми тук:

```
@Repository
public interface BrandRepository extends JpaRepository<BrandEntity, String> {

    Optional<BrandEntity> findByName(String name);
}
```

Което означава, че в следствие на тестовете си вкарал в ДБ два бранда с еднакво име. Ако името на бранда е уникално, направи колонката уникална. Така ще гръмваш много по-близо до грешката.

След всеки тест почиствай ДБ-то от останалите ентитита, защото освен ако не ползваш @DirtiesContext всичко си остава в ДБ между изпълненията. В общи линии, добра практика е:

1. `@BeforeEach` - initialized data
2. execute test
3. `@AfterEach` - clean up

Поздрави!

**Comment by TeoKarakashev** [comment]
Коничи уа! Много благодаря, Лъчо и много съжалявам, че те притеснявам пак, но сега си имплементирах интерсептор за page title и не мога да го подкарам да рарботи, добавих <title> в хедъра, но не иска да го захапе.

Гита си е същия: https://github.com/TeoKarakashev/Softuni-Spring-Web-Project

**Comment by luchob** [comment]
Гапротив, захапва го - пуснах го локално, работи, спира си на брейкпойнт, показва си тайтъла. Ето тайтъла:

<img width="270" alt="Screenshot 2021-03-31 at 20 53 25" src="https://user-images.githubusercontent.com/10339738/113188917-4d3a0e00-9263-11eb-90dc-edab37cc4e82.png">

На хоум пейджа:

<img width="698" alt="Screenshot 2021-03-31 at 20 53 39" src="https://user-images.githubusercontent.com/10339738/113188937-51662b80-9263-11eb-8ed2-8e5b191f4626.png">

**Comment by TeoKarakashev** [comment]
Проблемът е от браузъра, на другия работи, най-вероятно някаква настройка съм пипал, благодаря ти много!

Бързо оздравяване!
