### ISSUE TITLE
pdf in cloudinary

### ISSUE THREAD

**Issue by Elizabetaa** [luchob/softuni-music-db#27]
Здравй Лъчо! Може ли да се качва pdf в cloudinary и ако да как?

**Comment by luchob** [comment]
Привет!

Мммм.... Може да се качва, но очевидно не може да се сваля (by default) :-) Качва се както и image. 

Накратко:

_Based on a recent update to our security policies, we've restricted the ability of new free accounts to deliver PDFs and Archive files like `zip` or `rar`. It's possible to upload and manage those files, and it's possible to download them using our Media Library, but a restriction applies to delivering them publicly._

Повече детайли - [тук](https://support.cloudinary.com/hc/en-us/articles/360016480179-PDF-or-ZIP-files-appearing-in-Media-Library-but-download-URLs-return-an-error-).

Поздрави,
Л.
