### ISSUE TITLE
Проблем с тестовете на контролерите

### ISSUE THREAD

**Issue by DesislavaGetova-Petrova** [luchob/softuni-music-db#29]
Здравей Лъчо, моля те когато имаш възможност да погледнеш написаните от мен тестове за контролерите. Нещо явно пропускам и ми хвърля все една и съща грешка.   https://github.com/DesislavaGetova-Petrova/TheProject/tree/master/src/test/java/desico/project/web

**Comment by luchob** [comment]
Добра вечер, Деси!

Ако говориш за ето тази грешка:
```
Caused by: java.lang.IllegalStateException: Failed to replace DataSource with an embedded database for tests. If you want an embedded database please put a supported one on the classpath or tune the replace attribute of @AutoConfigureTestDatabase.
```

То това е защото нямаш H2 в pom.xml:
```
<dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
```

Следващия проблем обаче, е че application.yaml за тестовете не е на правилното място, трябва да е с една директория по-нагоре. Ето така:

<img width="303" alt="Screenshot 2021-03-31 at 21 54 00" src="https://user-images.githubusercontent.com/10339738/113195997-a148f080-926b-11eb-855d-6b599cb1ea54.png">

Последно - в тестовия yaml подравняването не е коректно и някои пропъртита липсват. Копирай оригиналния и настрой H2, така ще е най-лесно.

Поздрави,
Л.

**Comment by DesislavaGetova-Petrova** [comment]
Благодаря много, ще коригирам тези съществени пропуски. Лека вечер и извинявай за безпокойството!
