### ISSUE TITLE
security problem

### ISSUE THREAD

**Issue by AswAce** [luchob/softuni-music-db#30]
Здрасти като цяло мисля че успях да се справя и нямам проблеми всичко си ходи само където трябва. 
Единствено имам 1 път departments/department/* който трябва да е отворен за всички,но не ми зарежда преди да се логна.
интересното е че имам съвсем същия път ,но за докторите ми който работи.
https://github.com/AswAce/MedicalFiles/blob/main/src/main/java/medical/medical/files/config/security/SecurityConfiguration.java

**Comment by luchob** [comment]
Привет!

Ами... не съм сигурен, че докторите работят, защото е същия патърн, по скоро е заради това.
```
                antMatchers(
                       ...
                        "/doctors/doctor/*/examinations",
                        "/doctors/doctor/*/reviews").hasRole("DOCTOR").
```

Разгледай моля те ето [тази страничка](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html).

Или по-специално:

`* matches zero or more characters`

Това нещо: `/departments/department/*/` матчва:

`/departments/department/123/`но не и `/departments/department/123` :-) 

Поздрави,
Л!
