### ISSUE TITLE
Критики/препоръки относно личен проект

### ISSUE THREAD

**Issue by Hristiyan-Anchev** [luchob/softuni-music-db#31]
Здравей Лъчо,
Бих желал да ти представя моят проект, който ще защитавам пред Софтуни.
А именно , [Great Reviews](https://github.com/Hristiyan-Anchev/Great-Reviews) - опоскана версия на [Trustpilot](https://www.trustpilot.com) .

Към момента сайта е на 90% готов, и бих искал товята критика, и въобще разни неща, които са ти неприятни за очите на пръв поглед.
Има двама seed-нати юзъра, с парола passwd1, които са test@mail.com и admin@mail.com 

Като конкретни въпроси искам да попитам:
1. Коректно ли е да проверявам за ролята на конкретния потребител в самия route handler в комбинация с @PreAuthorize("isAuthenticated()") , вместо  директно @PreAuthorize("hasRole()").
2. Би ли ми дал насоки как да върна потребителя към предишната страница която е поискал преди да се логне.
    С други думи, ако анонимен потребител удари някой защитен route той бива пренасочен към /login ... та как мога да го 
    изпратя обратно към страницата която е поискал първоначално след като се логне.

EDIT:
  3. Как мога да избегна нарастването на контролер и сървис класовете.
      Струва ми се, че стават една голяма каша от методи, и че на места се нарушава Interface Segregation от SOLID 
     принципите.
    
    Благодаря за отделеното време!

**Comment by luchob** [comment]
Здравей!

Ще може ли да помоля да комитнеш и един application.properties/application.yaml :-) Със сигурност ще го разгледам, но ми е тегаво да го пусна без този файл.

Поздрави,
Л.

**Comment by Hristiyan-Anchev** [comment]
@luchob 
Съжалявам, въобще не съобразих че там има доста зависимости, без които ще е трудно.

[application.properties](https://pastebin.com/6bNJYaFL)

**Comment by luchob** [comment]
Привет, как е положението? :-)

По въпрос 1:

Ако секюрваш пътищата в твоя SpringAuthenticationConfig, там имаш необходимите инструменти да направиш не само аутентикация, но  и ауторизация на пътищата. Например:
```
.antMatchers("/x/y/z").hasRole("SPECIAL_DUDE")
```
В такъв случай не е необходим @Preauthorize върху метода. Бих се придържал към такава конфигурация.

По въпрос 2:

Това вече е много интересен въпрос, ако го подкараш драсни един ред. :-) Не съм го правил никога, но доколкото знам може да използваш `SavedRequestAwareAuthenticationSuccessHandler` който пази предния рекуест. Като го пробваш, ще съм ти благодарен ако драснеш един ред за да се
похвалиш дали става или не.

По въпрос 3:

Наистина става каша, наблюдавам го и в истинските проекти. Как се решава... най-вече с разделяне и с композиции. Например имахме един ASNService, после стана ASNService + ASNLifeCycleService, после още един се появи и т.н.. Излизат и отделни компоненти, и се правят композиции:

ServiceA {
  private ComponentA compA;
  private ComponentB compB;
}

И тъй. Иначе проекта ти е голям и добре структориран. Keep on!
