### ISSUE TITLE
search-bar-id Problem

### ISSUE THREAD

**Issue by Iliyan02** [luchob/softuni-music-db#32]
Здравей, Лъчо...отново:( ! Може ли да погледнеш защо при /home страницата филмите ми се зареждат с movie-page-details, когато избера някой филм, но когато го търся със search-bar-а не ми намира id-то. А има още един бъг със security. След като се логна и върна назад страницата..пак оставам логнат. Така ли трябва да е или..?
Благодаря много предварително!
https://github.com/Iliyan02/iMovieDemo

**Comment by luchob** [comment]
Здравей!

Не намира id-то... защото просто няма откъде да го намери. В `MovieViewModel` няма поле `id`. За това аз съм виновен, защото като рефакторирах оня ден не го добавих. Просто си добави поле id.  Аз вече оправих musicdb, защото един колега ми направи забележка :-) Това със секюритито не е бъг в никакъв случай не трябва да те притеснява.

Поздрави,
Л.
