### ISSUE TITLE
Cleaning test database issue

### ISSUE THREAD

**Issue by StanislavI285** [luchob/softuni-music-db#35]
Привет, Лъчо,

Поредния проблем с тестовете - при NewsControllerTest тестът минава, само ако зачистването на репозиторитата е в BeforeEach, а ако го сложа в AfterEach се чупи. 
Същото и при UserControllerTest, ако имам зачистване с AfterEach, хвърля  грешка. Както и като опитам да запазя roleEntity в базата при инициализирането, за да мога да го сетна на user-a.(хвърля org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation), т.е. че съществува вече в базата, ако правилно разбирам.
Не мога да му схвана логиката как и кога иска да се изчиства базата.

Edit: Включих още един тест за добавяне на статия. Има добавен csrf() към рикуеста, но връща:

MockHttpServletResponse:
           Status = 403
    Error message = Forbidden
          Headers = [X-Content-Type-Options:"nosniff", X-XSS-Protection:"1; mode=block", Cache-Control:"no-cache, no-store, max-age=0, must-revalidate", Pragma:"no-cache", Expires:"0", X-Frame-Options:"DENY"]
     Content type = null
             Body = 
    Forwarded URL = null
   Redirected URL = null
          Cookies = []

[https://github.com/StanislavI285/SpringWebProject](url)

Поздрави,
Станислав

**Comment by luchob** [comment]
Привет!

За грешката 403. Тестът ти е анотиран по този начин:

```
    @Test
    @WithMockUser(username = "username", roles = {"ADMIN", "USER"})
```

А в секюрити конфигурацията имаш

```
    antMatchers("/news/add"...).hasAuthority("ROLE_MODERATOR")
```

От където и 403, защото `username` не е модератор. :-)

За другата грешка с ref. integrity. В ролята имаш:

```
    @Column(name = "name", unique = true)
    @Enumerated(EnumType.STRING)
```

Колонката е уникална, т.е. не може да имаш х2 ADMIN, например. Но се опитваш да инсъртнеш роля два пъти, когато се стартира теста. Един път с класа DBInit, друг път в самия тест, откъдето идва и проблема. В теста не трябва да инсъртваш роля, вземи си я през role repository-то.

Поздрави,
Л.

**Comment by StanislavI285** [comment]
Много ти благодаря!
