### ISSUE TITLE
Delete problem

### ISSUE THREAD

**Issue by Iliyan02** [luchob/softuni-music-db#36]
Лъчо, здравей! Имам дребен проблем при триенето на филм от базата. Не мога да изтрия филм, който го добавям през admin профила, но мога да изтрия такъв, който е хардкоднат от json. Нещо се бъркат id-тата с тези на aop-log-a.
https://imgur.com/Cik3zsX - ето я грешката.
https://github.com/Iliyan02/iMovieDemo

**Comment by luchob** [comment]
Привет!

Проблемът ти е не в ID-тата, а че имаш ентри в logs таблицата, което сочи твоето movie. Има форейн кей. Варианти:

1. Да изтриеш logs (например с JPQL) за това movie.
2. Да направиш релацията bidirectional и да имаш Cascade REMOVE :(
3. Да пазиш movie ID в logs, едва ли ти трябва да имаш достъп до ентитито.

Поздрави,
Л.
