### ISSUE TITLE
Проблем с in-memory DB

### ISSUE THREAD

**Issue by Pavkata00** [luchob/softuni-music-db#37]
Здравей, Лъчо.

Не знам защо, но при мен не се вдига база при рънването на тестовете и всичко ми запазва в основната база данни.
Опитах с resource папка... hsql, също така h2  и @AutoConfigureTestDatabase и всеки път гърми.. мисля, че пропускам нещо някъде.

Някакви идеи как да я подкарам?

https://github.com/Pavkata00/Wine-Business

**Comment by luchob** [comment]
Здрасти!

Категорично се вдига in memory база и това личи по ексепшъните:

```
Caused by: org.hsqldb.HsqlException: type not found or user lacks privilege: TEXT
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
```

В текущото състояние на проекта, обаче имаш в application.yaml настроен диалект за H2 а в pom.xml - HSQLDB. Това са различни бази, така че трябва да се спреш на една, например h2. Тогава в pom.xml трябва да махнеш HSQL и да добавиш H2.

```
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
```

С това проблемите няма да свършат. Много са погрешни ето тези методи:

```
public interface RoleService {

    RoleEntity getAdminRole();

    RoleEntity getUserRole();
}
```

Никога не може да си сигурен коя база какви ИД-та ще ти сложи при инит. Затова опитай нещо от сорта:

```
    @Override
    public RoleEntity getAdminRole() {
        return this.roleRepository.
            findByRole(RoleEnum.ADMIN).
            orElseThrow(() -> new IllegalStateException("Please initialize the ADMIN role!"));
    }
```

В репото нещо подобно:

```
public interface RoleRepository extends JpaRepository<RoleEntity, Long> {
    Optional<RoleEntity> findByRole(RoleEnum roleEnum);
}
```

Тогава вече теста за регистрацията стана зелен...

Поздрави,
Л.

**Comment by Pavkata00** [comment]
Благодаря много за помощта! :)
