### ISSUE TITLE
проблем с Environment Variables 

### ISSUE THREAD

**Issue by AswAce** [luchob/softuni-music-db#40]
Здрасти всеки път след пуснати тестове на апа ми изчезват  Environment Variables и кода гърми защото нямам cloudinary_key  аз мога пак да го добавя, но ми се струва че това не трябва да се  прави всеки път ?

**Comment by luchob** [comment]
Привет!

Не, изобщо не трябва да го правиш. Env. variables се ползват, за да настроиш приложението да върви в определена среда, затова се казват така. Например, с тях подаваш ключове, различни настройки (напр. някакви cron-ове) и т.н. Тестовете са друга бира. Те обикновено не разчитат на env. variables, особено тестовете които правим в нашите проекти. Хубаво е те да разчитат на твърди стойности, напримрер:
```
cloudinary:
    api-key: test_key
    api-secret: test_secret
```

В тестовете си, ти няма да се свържеш към истинското клаудинари. По-скоро, ще използваш `@MockBean` за да мокнеш клаудинари сървиса. Така че, в тестовото си application.yaml може да изчистиш всички env. variables и проблема е решен.

Поздрави,
Л.

**Comment by AswAce** [comment]
Да аз така съм направил в тестовото поперти са ми сложени примерни стойности, но когато направя тест и после си подкарам апликацията са ми се итрили EV.

**Comment by luchob** [comment]
Привет отново! Нямам идея как стартираш приложението си, но допускам, че е от "конфигурация", която IntelliJ създава за теб като пуснеш нещо за първи път. Показвам на скрийншот:

<img width="354" alt="Screenshot 2021-04-08 at 9 09 02" src="https://user-images.githubusercontent.com/10339738/113976779-3c346280-984a-11eb-8b7d-347093e155eb.png">

Тези кофигурции може да са временни или постоянни в проекта ти, като може да имаш максимум 5 временни. Предполагам там се корени проблема. Пускам линк към статийка как може да си създадеш постоянна такава, където да пазиш env vars:

https://www.jetbrains.com/help/idea/run-debug-configuration.html

Поздрави,
Л.
