### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by ZBashev** [luchob/softuni-music-db#41]
Здравейте,в логин формата една от буквите на username я въвеждам ,като голяма буква и въпреки това ме логва. Къде да търся проблема или може би трябва да направя допълнителна логика за това. Също така в една от лекции донесохте скенер за баркодове.  Къде мога да прочета и да разбера повече относно как може да се четат различни баркодове от различни идващи фирми. Или трябва да са предварително въведени ,като модел от всяка една фирма(вид етикет).
Благодаря 
Поздрави

**Comment by luchob** [comment]
Здравей!

Проблемът с логина и малките и главни букви притесни и друг колега. Виж тук - https://github.com/luchob/softuni-spring-advanced-2021/issues/13

Най-простите скенери се разпознават като... клавиатури :-) Например. В Андроид е малко по сложно. Но... Баркодовете обикновено са стандартни, напр. EAN - https://en.wikipedia.org/wiki/International_Article_Number

Те се четат до т.нар. GTIN (виж статията). Ако искаш да правиш таково нещо, смятам че трябва да имаш предварително въведени стоки.

Поздрави,
Л.
