### ISSUE TITLE
Благодарности за обучението и един въпрос

### ISSUE THREAD

**Issue by br-ml** [luchob/softuni-music-db#42]
Здравей Лъчо, 

Първо благодарности за обучението.
Имам един малко страничен въпрос. 
Представи си Java приложение, което не е писано със Spring и искам да направя едно допълнително под-приложение към него(само ще ползва частично базата на основното приложение.) 
Въпросът ми е, би ли станало по-тежко/бавно цялото приложение, ако под-приложението го разпиша със spring или по-добре е да си се пише всичко без spring. 

Въпросът не е много конретен и мако абсрактен, но ако можеш да изкажеш мнение сподели.

Поздрави 

Брани

**Comment by luchob** [comment]
Здравей!

Надявам се, че и ти и колегите са научили някакви полезни неща и че изпита е приключил успешно.

Въпросът е наистина малко абстрактен, звучи ми странно "подприложение" на едно приложение да е спринг, останалото да не е... :no_mouth: Не знам странно ми е, подобно нещо съм виждал веднъж - някой беше измъкнал [стейт машината ](https://spring.io/projects/spring-statemachine) на спринг и беше плясната в отделен проект и не бях особено очарован... Но може би за работа с ДБ ще изглежда малко по-добре. Още повече, ако имаш достъп до една база със и без спринг може да се появят проблеми.

Не знам дали ще стане по-бавно - вероятно не. Дали ще стане по-тежко - вероятно да. 


Поздрави,
Л.
