### ISSUE TITLE
Въпрос

### ISSUE THREAD

**Issue by AswAce** [luchob/softuni-music-db#44]
Здрасти.
Знам че вече кърса мина ,но случайно ако имаш време.
Правя си една апликация в която правя fetch get заявка  в js файл от Google form данни.
След това с функция си го преобразувам в обек който ми върши работа.
После искам във същия js файл без да го визуализирам нарпаво да направя fetch POST към конторлера ми в Spring апликацията но нещата не се получават.
Това е кода:
Controller: https://github.com/AswAce/HR_Resumes/blob/main/platform/src/main/java/hr/platform/web/TestRestController.java
JS file: https://github.com/AswAce/HR_Resumes/blob/main/platform/src/main/resources/static/js/import.js
Кото кода е още доста басик.
Идеята е че просто го искам във POJO на бек енда дали ще е с REST CONTROLLER или Controller няма голямо значение.

**Comment by luchob** [comment]
Привет!

Не става да, защото POST заявката очаква да имаш CSRF токен ;-) 

Поздрави!
