### ISSUE TITLE
Имам проблем ApplicationSecurityConfig

### ISSUE THREAD

**Issue by BojidarVn** [luchob/softuni-music-db#7]
Когато отворя страничката с ApplicationSecurityConfig ми подчерта в червено musicDBUserService когато цъкна на съобщението ми изписва -  Could not autowire. No beans of 'MusicDBUserService' type found. 
Проекта ми работи нормално. Стигнал съм до events. 
Днеска след като го стартирах без да правя нещо почна да свети всичко в червено.
При базите с данни ми излезе от някъде някакво си hibenate база с данни изтрих го и се повечето неща се оравиха, но това остана да свети. Незнам какво точно се случва ако можеш да ми кажеш защо се случва и как да се оправи ще съм благодарен. 
https://github.com/BojidarVn/softUni-Music-DB

**Comment by luchob** [comment]
Хей, привет!

При мен изглежда ОК:

<img width="906" alt="Screenshot 2021-03-15 at 22 47 43" src="https://user-images.githubusercontent.com/10339738/111219311-85ddb480-85e0-11eb-942f-2ab74ba42e57.png">

Което ме навежда на мисълта, че има някакъв проблем при теб. Може би:

1. Изпълни `gradlew clean`
2. Затвори IntelliJ и изтрий всички папки, които са на идеята и билд-а
3. Импортни проекта наново.

Ако не стане дори и така, изтрий проекта и го импортни отново. Би трябвало да сработи.

Драсни един ред като опиташ...

Поздрави,
Л.

**Comment by BojidarVn** [comment]
FieldMach

ArtistService

UserService

Всички светнаха в червено и нз защо сега ми казва като стартирвам
приложението ,че

"Parameter 0 of constructor in bg.softuni.musicdb.WEB.HomeController
required a bean of type 'bg.softuni.musicdb.service.CarouselService' that
could not be found."


Оправих го като преписах на ново проекта.

На пн, 15.03.2021 г. в 22:50 ч. Lachezar Balev ***@***.***>
написа:

**Comment by luchob** [comment]
Здравей! 

По първия въпрос - загадка е защо всичко ти е червено. Добре... никакво пренаписване на нищо. Просто:

1. Изтрий си проекта
2. направи нов git clone 
3. Отвори и напред

По втория въпрос съобщението за грешка е доста говорящо:

```
required a bean of type 'bg.softuni.musicdb.service.CarouselService' that could not be found
```

Кога един клас става spring bean? Когато го обявиш за @Component, @Service или го декларираш в конфикурация с Bean. В твоят проек имплементацията на каросел сървиса не е анотирана, по някаква причина:
```
public class CarouselServiceImpl implements CarouselService {
```

Нека стане сървис:

```
@Service
public class CarouselServiceImpl implements CarouselService {
```

и ще тръгне :-) 

Поздрави, Л.
