### ISSUE TITLE
Optional values in edit profile - total fail for now

### ISSUE THREAD

**Issue by Stefan-Markov** [luchob/softuni-music-db#9]
Добър вечер, искам да приключа с имплементацията по логиката на проекта, но удрям греда с optional полета в промяна на профила на user. Уж @Size пуска  null стойности, но не става, bindingResulta винаги хваща празните полета. Целта ми е в profile/edit/{username}   usera да въведе само желаните за промяна данни и оттам аз ще си ги прихвана в service кое да ъпдейтна. Дали има някакво решение.

https://github.com/StefanFMarkov/Motorious

**Comment by luchob** [comment]
:( https://github.com/luchob/softuni-music-db/issues/10

**Comment by luchob** [comment]
Здравей! Вече имам някакви моменти, в които се съвземам :-) Още ли го има този проблем? Виждам, че ползваш @Length?

**Comment by Stefan-Markov** [comment]
Здравейте, надявам се вече да сте по-добре. Проекта съм го качил обновен в профила ми. Използвах binding model и  ако user-a иска да ъпдейтне инфо (първо име, второ име, снимка или парола) трябва цялата информация да въведе иначе няма да го пусне bindinga. Иначе с @Size и @Length не ме пускаше и затова го направих така.  Като отгоре на страничката съм подал сегашната информация на user-a да не се чуди каква му е.
https://github.com/StefanFMarkov/Motorious

**Comment by luchob** [comment]
Здравей! Ами... Отново зависи какво искаш да направиш. Принципно, виждам един вариант, който ми се струва ОК в твоя случай. Ако очакванията при CREATE и UPDATE са съвсем различни, бих заложил на 2 различни байндинг модела, никой не е казал, че е необходимо байндинг модела ти да е само 1 :-)
